
name: CI-CD-AWS-test
env:
  EB_PACKAGE_S3_BUCKET_NAME : "test-kuldeep"
  EB_APPLICATION_NAME       : "Test-Kuldeep"
  EB_ENVIRONMENT_NAME       : "Testkuldeep-env"
  DEPLOY_PACKAGE_NAME       : "django-app-${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-west-2"


on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Git clone on our repository
        uses: actions/checkout@v2

      - name: Create zip deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_KK }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_KK }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Copy our deployment package to S3 bucket
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
      - name: Print nice message on success finish
        run: echo "CI Pipeline part finished successfuly"
        
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_KK }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_KK }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Create new EBL Application version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ env.EB_APPLICATION_NAME }} \
          --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
          --version-label "${{ github.sha }}"
          
      - name: Deploy new app
        run: aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "${{ github.sha }}"
        
      - name: Print nice message on success finish
        run: echo "CD part finished successfuly"
